---
name: hazel

releases:
- name: hazel
  version: 0.0.1+dev.10

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000



instance_groups:
- name: hazel
  azs: [z1]
  instances: 1
  jobs:
  - name: hazel
    release: hazel
  vm_type: default
  stemcell: default
  networks:
  - name: default


